### ISSUE TITLE
code going to infinite loop

### ISSUE THREAD

**Issue by codescool** [manthan89-py/Plant-Disease-Detection#6]
![image](https://user-images.githubusercontent.com/89523675/219561071-d89fee58-7f60-42c9-b7e0-5e43d95f9403.png)
This part of code is going to infinite loop, not getting any result eventhough it kept running over night

**Comment by hwj20122535** [comment]
I have the same problem as you.  Have you solved this problem?

**Comment by manthan89-py** [comment]
It will take a lot of time if you are using a CPU to train this model. We have a huge dataset and complex model architecture which is why it is taking too much time to train. I have trained it on GPU So that's why it takes hardly 25-30 minutes for me. 

You can try it out by reducing the dataset size or model complexity.
