### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by Sanjusanjay29** [manthan89-py/Plant-Disease-Detection#7]
if iam uploading leaf image from the google it showing wrong result .what to do now

**Comment by Govind-Dwivedi** [comment]
ML results are not always right. The main reason that your result was wrong may be because of the type of image that you uploaded was not present in the dataset while training. Suppose you uploaded an apple leaf's image form a farm with lots of apples in background, but in the dataset all the apple leaf images had pink background and they were all putting on floor. So, in this case, model would have hard time giving correct result. So, the main thing is that **dataset should be diverse enough** to cover lots of situations. So, what can you do? You can try searching for more diverse dataset or if you are happy with results just go with it.
